# Generated by Django 4.1.4 on 2022-12-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(null=True, verbose_name='Ссылка на гитхаб'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='database/images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.FileField(upload_to='database/files', verbose_name='Файл'),
        ),
    ]
