# Generated by Django 4.1.4 on 2022-12-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_project_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на гитхаб'),
        ),
    ]
