# Generated by Django 4.0.6 on 2022-12-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_project_github_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='website_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на сайт'),
        ),
    ]
